name: files
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  grpc: ^4.0.1
  protobuf: ^3.1.0
  stormberry: ^0.13.1
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.5
  encrypt: ^5.0.3
  minio: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
